### PR TITLE
Average bench: Run more than one time

### PR DESCRIPTION
**Pull request by Kikobeats**
Fixes https://github.com/dominictarr/bench-lru/issues/8

Now the result is based on a average result of run the same bench 5 times.

Outuput:

| name                                                | size    | gzip    | set  | get1  | update | get2  | evict |
|-----------------------------------------------------|---------|---------|------|-------|--------|-------|-------|
| [lru-fast](https://npm.im/lru-fast)                 | 2.34 kB | 793 B   | 6879 | 25253 | 18651  | 21862 | 3806  |
| [tiny-lru](https://npm.im/tiny-lru)                 | 4 kB    | 1.64 kB | 6419 | 16244 | 18303  | 15313 | 4772  |
| [lru_cache](https://npm.im/lru_cache)               | 2.19 kB | 756 B   | 4769 | 14952 | 14257  | 15804 | 4149  |
| [simple-lru-cache](https://npm.im/simple-lru-cache) | 1.43 kB | 565 B   | 3351 | 16401 | 9387   | 17188 | 3841  |
| [hyperlru](https://npm.im/hyperlru)                 | 541 B   | 339 B   | 2106 | 17048 | 2258   | 20525 | 2322  |
| [hashlru](https://npm.im/hashlru)                   | 628 B   | 332 B   | 4168 | 5539  | 5401   | 6500  | 6314  |
| [lru-cache](https://npm.im/lru-cache)               | 19.1 kB | 6.23 kB | 1225 | 5392  | 3826   | 5621  | 953   |
| [lru](https://npm.im/lru)                           | 6.07 kB | 1.86 kB | 2801 | 4087  | 3635   | 4102  | 1345  |
| [secondary-cache](https://npm.im/secondary-cache)   | 22.6 kB | 6.54 kB | 1617 | 2875  | 2695   | 5948  | 1336  |
| [quick-lru](https://npm.im/quick-lru)               | 1.23 kB | 489 B   | 2585 | 2130  | 2667   | 2121  | 2411  |
| [modern-lru](https://npm.im/modern-lru)             | 2.27 kB | 907 B   | 1057 | 2446  | 2033   | 2415  | 685   |
| [mkc](https://npm.im/mkc)                           | 10.5 kB | 3.61 kB | 808  | 1286  | 790    | 1407  | 584   |

### CODE REVIEW

**Comment by Kikobeats** [comment]
What do you think @SkeLLLa?

**Comment by SkeLLLa** [comment]
After couple of runs the results vary, but they are pretty much the same. So, it's definitely looks better.

**Comment by avoidwork** [comment]
@Kikobeats no semicolons / statement terminators make this look bad in an IDE; there is no benefit from not putting them in, only eventual errors when people make mistakes.

**Comment by Kikobeats** [comment]
The project use standard as linter: https://github.com/dominictarr/bench-lru/blob/master/package.json#L46

**Comment by avoidwork** [comment]
that is true, and i don't like it; it's problematic as shown in that code screenshot.  <-- opinion/fact mix

it wastes energy on my laptop <-- fact ... nothing is for free

**Comment by dominictarr** [comment]
@avoidwork not everyone uses the same IDE as you! if you want to waste everyone's time, complain about whitespace or semicolons. If you wanna make friends and get on with things, just ignore the things that do not really matter.

**Comment by avoidwork** [comment]
@dominictarr i write code for the JIT, so you can look at this as some semicolon fanboy rant, or you can take it at face value that the code is not as fast as it could, and is wasting power as it's re-written every time it executes.

has nothing to do being friendly, and you're reading it with a negative bias.

**Comment by avoidwork** [comment]
just an example of where my brain is at in this current code...

current forward iteration:
```console
| name                                                | size    | gzip    | set  | get1  | update | get2  | evict |
|-----------------------------------------------------|---------|---------|------|-------|--------|-------|-------|
| [lru-fast](https://npm.im/lru-fast)                 | 2.34 kB | 793 B   | 6830 | 34500 | 21401  | 26732 | 4155  |
| [tiny-lru](https://npm.im/tiny-lru)                 | 4.76 kB | 1.65 kB | 8149 | 15262 | 17175  | 18970 | 5347  |
| [lru_cache](https://npm.im/lru_cache)               | 2.19 kB | 756 B   | 4504 | 19075 | 8427   | 21970 | 4371  |
| [simple-lru-cache](https://npm.im/simple-lru-cache) | 1.43 kB | 565 B   | 3317 | 19634 | 7682   | 20153 | 4061  |
| [hashlru](https://npm.im/hashlru)                   | 628 B   | 332 B   | 5393 | 6464  | 4997   | 6259  | 5094  |
| [hyperlru-object](https://npm.im/hyperlru-object)   | 433 B   | 265 B   | 1224 | 6555  | 7155   | 10792 | 1352  |
| [lru](https://npm.im/lru)                           | 6.07 kB | 1.86 kB | 2664 | 3819  | 3864   | 3982  | 1401  |
| [secondary-cache](https://npm.im/secondary-cache)   | 22.6 kB | 6.54 kB | 1593 | 3526  | 2486   | 5714  | 1539  |
| [hyperlru-map](https://npm.im/hyperlru-map)         | 329 B   | 232 B   | 1005 | 3978  | 4077   | 4380  | 900   |
| [lru-cache](https://npm.im/lru-cache)               | 19.1 kB | 6.23 kB | 1152 | 4631  | 2828   | 4193  | 857   |
| [quick-lru](https://npm.im/quick-lru)               | 1.23 kB | 489 B   | 3191 | 1936  | 2848   | 2278  | 3036  |
| [modern-lru](https://npm.im/modern-lru)             | 2.27 kB | 907 B   | 1067 | 2310  | 1882   | 2256  | 667   |
| [mkc](https://npm.im/mkc)                           | 10.5 kB | 3.61 kB | 870  | 1414  | 867    | 1499  | 571   |
```

and if you simply reverse the array...
```console
| name                                                | size    | gzip    | set  | get1  | update | get2  | evict |
|-----------------------------------------------------|---------|---------|------|-------|--------|-------|-------|
| [lru_cache](https://npm.im/lru_cache)               | 2.19 kB | 756 B   | 3580 | 21915 | 14499  | 24643 | 4267  |
| [tiny-lru](https://npm.im/tiny-lru)                 | 4.76 kB | 1.65 kB | 8844 | 16199 | 19521  | 16779 | 5368  |
| [lru-fast](https://npm.im/lru-fast)                 | 2.34 kB | 793 B   | 7786 | 17767 | 14052  | 18859 | 4693  |
| [simple-lru-cache](https://npm.im/simple-lru-cache) | 1.43 kB | 565 B   | 4426 | 15885 | 9618   | 19449 | 4303  |
| [hyperlru-object](https://npm.im/hyperlru-object)   | 433 B   | 265 B   | 1308 | 9605  | 10362  | 11546 | 1321  |
| [hashlru](https://npm.im/hashlru)                   | 628 B   | 332 B   | 5381 | 6576  | 5374   | 6133  | 6420  |
| [lru](https://npm.im/lru)                           | 6.07 kB | 1.86 kB | 3214 | 3840  | 3740   | 4437  | 1616  |
| [secondary-cache](https://npm.im/secondary-cache)   | 22.6 kB | 6.54 kB | 1893 | 3181  | 3090   | 6621  | 1357  |
| [lru-cache](https://npm.im/lru-cache)               | 19.1 kB | 6.23 kB | 1419 | 3737  | 2569   | 4503  | 926   |
| [quick-lru](https://npm.im/quick-lru)               | 1.23 kB | 489 B   | 2797 | 2158  | 2392   | 2085  | 2969  |
| [hyperlru-map](https://npm.im/hyperlru-map)         | 329 B   | 232 B   | 989  | 3273  | 3316   | 3566  | 828   |
| [modern-lru](https://npm.im/modern-lru)             | 2.27 kB | 907 B   | 1161 | 2477  | 1955   | 2457  | 731   |
| [mkc](https://npm.im/mkc)                           | 10.5 kB | 3.61 kB | 780  | 1343  | 899    | 1516  | 711   |
```

you can see the recent rewrite doesn't really address the underlying problem of the JIT's ICs; this benchmark needs to run in n child processes to avoid pollution. my lib stays in #2 cause ... written for the JIT.

**Comment by Kikobeats** [comment]
@avoidwork Can you make a PR? talk is cheap, show me the code 😄

**Comment by avoidwork** [comment]
yeah, of course. i got something in my utility belt for that kind of job called `tiny-worker` ;)

**Comment by avoidwork** [comment]
i can likely land something on the weekend; i got some priority work to handle a head of it. i'm curious to see what splitting things up do, because there will be less `gc` issues in theory.

**Comment by dominictarr** [comment]
@avoidwork if you think that semicolons are _faster_ then write a benchmark that demonstrates that and we can settle this pointless argument once and for all.

**Comment by dominictarr** [comment]
👍 on running each thing in it's own process!

**Pull request merged**
