### PR TITLE
Improve format

### PR DESCRIPTION
**Pull request by Kikobeats**
I make results more legible and try to unify sections. What do you think?

### CODE REVIEW

**Comment by dominictarr** [comment]
thanks how did you use a tool to generate the table?
I had just pasted the new results at the bottom because I was too lazy to rewrite the discussion, i guess I should just do that.

**Comment by Kikobeats** [comment]
I use this https://github.com/mplewis/csvtomd/blob/master/README.md

**Comment by dominictarr** [comment]
aha, okay cool, also found this: https://www.npmjs.com/package/csv2md

**Comment by dominictarr** [comment]
thanks merged into 1.0.0

**Comment by Kikobeats** [comment]
Maybe we can use a npm package for automatizate the process, like https://www.npmjs.com/package/csv-to-md

**Comment by dominictarr** [comment]
yup, lets do that next time we add something to the the benchmark

**Comment by dominictarr** [comment]
btw, can use https://github.com/dominictarr/carpenter to automatically embed the results.

**Comment by Kikobeats** [comment]
sounds nice!

**Pull request merged**
